// <auto-generated />
using System;
using Jason.Runtime.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jason.Runtime.Persistence.Migrations
{
    [DbContext(typeof(JasonDbContext))]
    [Migration("20260919064112_ManagerEscalation")]
    partial class ManagerEscalation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Jason.Runtime.Persistence.Approval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BindingIdentity")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("binding_identity");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedById")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("decided_by_id");

                    b.Property<string>("DecidedByType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("decided_by_type");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("decision_reason");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("operation");

                    b.Property<int>("OperationVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("operation_version");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("plugin_id");

                    b.Property<string>("PluginSnapshotId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("plugin_snapshot_id");

                    b.Property<string>("Preview")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("preview_json");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_at");

                    b.Property<string>("RouteScope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("route_scope");

                    b.Property<string>("RoutingSnapshotId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("routing_snapshot_id");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_json");

                    b.Property<string>("SubjectHash")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_hash");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id")
                        .HasName("pk_approvals");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_approvals_campaign_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_approvals_public_id");

                    b.HasIndex("WorkItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_approvals_one_pending_per_item")
                        .HasFilter("status = 'pending'");

                    b.HasIndex("Status", "RequestedAt")
                        .HasDatabaseName("ix_approvals_status_requested_at");

                    b.ToTable("approvals", t =>
                        {
                            t.HasCheckConstraint("ck_approvals_preview_json", "json_valid(preview_json)");

                            t.HasCheckConstraint("ck_approvals_subject_json", "json_valid(subject_json)");
                        });
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.Attempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("claimed_at");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("command");

                    b.Property<string>("ContextSnapshot")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("context_snapshot_json")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_json");

                    b.Property<string>("ExecutionProfile")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_profile");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<string>("Launch")
                        .HasColumnType("TEXT")
                        .HasColumnName("launch_json");

                    b.Property<DateTime>("LockUntil")
                        .HasColumnType("TEXT")
                        .HasColumnName("lock_until");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("number");

                    b.Property<string>("Provenance")
                        .HasColumnType("TEXT")
                        .HasColumnName("provenance_json");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id")
                        .HasName("pk_attempts");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_attempts_public_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_attempts_status");

                    b.HasIndex("WorkItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_attempts_one_live_per_item")
                        .HasFilter("status IN ('scheduled','running')");

                    b.HasIndex("WorkItemId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_attempts_work_item_id_number");

                    b.ToTable("attempts", t =>
                        {
                            t.HasCheckConstraint("ck_attempts_context_snapshot_json", "json_valid(context_snapshot_json)");

                            t.HasCheckConstraint("ck_attempts_error_json", "error_json IS NULL OR json_valid(error_json)");

                            t.HasCheckConstraint("ck_attempts_launch_json", "launch_json IS NULL OR json_valid(launch_json)");
                        });
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at");

                    b.Property<string>("Context")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("context_json")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExecutionProfile")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_profile");

                    b.Property<int>("ManagerEventWatermark")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("manager_event_watermark");

                    b.Property<DateTime?>("ManagerReviewAnchor")
                        .HasColumnType("TEXT")
                        .HasColumnName("manager_review_anchor");

                    b.Property<int?>("ManagerReviewSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manager_review_seconds");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_campaigns");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_campaigns_public_id");

                    b.ToTable("campaigns", t =>
                        {
                            t.HasCheckConstraint("ck_campaigns_context_json", "json_valid(context_json)");
                        });
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.CampaignContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("campaign_id");

                    b.Property<int>("ContactId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("contact_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_campaign_contacts");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_campaign_contacts_contact_id");

                    b.HasIndex("CampaignId", "ContactId")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_contacts_campaign_id_contact_id");

                    b.ToTable("campaign_contacts");
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.CampaignRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Binding")
                        .HasColumnType("TEXT")
                        .HasColumnName("binding_json");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Operation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("operation");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("plugin_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_campaign_routes");

                    b.HasIndex("CampaignId")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_routes_one_default_per_campaign")
                        .HasFilter("operation IS NULL");

                    b.HasIndex("CampaignId", "Operation")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_routes_campaign_id_operation");

                    b.ToTable("campaign_routes", t =>
                        {
                            t.HasCheckConstraint("ck_campaign_routes_binding_json", "binding_json IS NULL OR json_valid(binding_json)");
                        });
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Custom")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("custom_json")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("time_zone");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_contacts_public_id");

                    b.ToTable("contacts", t =>
                        {
                            t.HasCheckConstraint("ck_contacts_custom_json", "json_valid(custom_json)");
                        });
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.ContactChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<int>("ContactId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("contact_id");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_json");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_primary");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_contact_channels");

                    b.HasIndex("Channel", "Value")
                        .HasDatabaseName("ix_contact_channels_channel_value");

                    b.HasIndex("ContactId", "Channel")
                        .IsUnique()
                        .HasDatabaseName("ix_contact_channels_one_primary_per_channel")
                        .HasFilter("is_primary = 1");

                    b.HasIndex("ContactId", "Channel", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_contact_channels_contact_id_channel_value");

                    b.ToTable("contact_channels", t =>
                        {
                            t.HasCheckConstraint("ck_contact_channels_data_json", "data_json IS NULL OR json_valid(data_json)");
                        });
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.Decision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("answer");

                    b.Property<string>("AnswerJournalEntryId")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("answer_journal_entry_id");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("answered_at");

                    b.Property<string>("AnsweredById")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("answered_by_id");

                    b.Property<string>("AnsweredByType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("answered_by_type");

                    b.Property<int>("AttemptId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_id");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("campaign_id");

                    b.Property<string>("ChosenOption")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("chosen_option");

                    b.Property<string>("Options")
                        .HasColumnType("TEXT")
                        .HasColumnName("options_json");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("question");

                    b.Property<DateTime>("RaisedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("raised_at");

                    b.Property<string>("References")
                        .HasColumnType("TEXT")
                        .HasColumnName("references_json");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id")
                        .HasName("pk_decisions");

                    b.HasIndex("AnswerJournalEntryId")
                        .HasDatabaseName("ix_decisions_answer_journal_entry_id");

                    b.HasIndex("AttemptId")
                        .HasDatabaseName("ix_decisions_attempt_id");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_decisions_campaign_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_decisions_public_id");

                    b.HasIndex("WorkItemId")
                        .HasDatabaseName("ix_decisions_work_item_id");

                    b.HasIndex("Status", "RaisedAt")
                        .HasDatabaseName("ix_decisions_status_raised_at");

                    b.ToTable("decisions", t =>
                        {
                            t.HasCheckConstraint("ck_decisions_options_json", "options_json IS NULL OR json_valid(options_json)");

                            t.HasCheckConstraint("ck_decisions_references_json", "references_json IS NULL OR json_valid(references_json)");
                        });
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.ExecutionProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentRevision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_revision");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_execution_profiles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_execution_profiles_name");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_execution_profiles_public_id");

                    b.ToTable("execution_profiles");
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.ExecutionProfileRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Args")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("args_json")
                        .HasDefaultValueSql("'[]'");

                    b.Property<string>("CliCommand")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("cli_command");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CreatedByType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_type");

                    b.Property<string>("Deny")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("deny_json")
                        .HasDefaultValueSql("'[]'");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("host");

                    b.Property<string>("HostVersionVerified")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("host_version_verified");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("number");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("profile_id");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("program");

                    b.HasKey("Id")
                        .HasName("pk_execution_profile_revisions");

                    b.HasIndex("ProfileId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_execution_profile_revisions_one_per_number");

                    b.ToTable("execution_profile_revisions", t =>
                        {
                            t.HasCheckConstraint("ck_execution_profile_revisions_args_json", "json_valid(args_json)");

                            t.HasCheckConstraint("ck_execution_profile_revisions_deny_json", "json_valid(deny_json)");
                        });
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.ExternalId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("campaign_id");

                    b.Property<int?>("ContactId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("contact_id");

                    b.Property<DateTime?>("DivergedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("diverged_at");

                    b.Property<string>("DivergedByAttemptId")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("diverged_by_attempt_id");

                    b.Property<string>("DivergedValue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("diverged_value");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("plugin_id");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at");

                    b.Property<string>("RecordedByAttemptId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_by_attempt_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_external_ids");

                    b.HasIndex("CampaignId", "PluginId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_external_ids_campaign_id_plugin_id_kind");

                    b.HasIndex("ContactId", "PluginId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_external_ids_contact_id_plugin_id_kind");

                    b.ToTable("external_ids", t =>
                        {
                            t.HasCheckConstraint("ck_external_ids_one_entity", "(contact_id IS NOT NULL AND campaign_id IS NULL) OR (contact_id IS NULL AND campaign_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_type");

                    b.Property<string>("AttemptId")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("attempt_id");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("New")
                        .HasColumnType("TEXT")
                        .HasColumnName("new_json");

                    b.Property<string>("Old")
                        .HasColumnType("TEXT")
                        .HasColumnName("old_json");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("TEXT")
                        .HasColumnName("ts");

                    b.Property<string>("WorkItemId")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id")
                        .HasName("pk_journal");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_journal_kind");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_public_id");

                    b.HasIndex("CampaignId", "Id")
                        .HasDatabaseName("ix_journal_campaign_id_id");

                    b.HasIndex("CampaignId", "PublicId")
                        .HasDatabaseName("ix_journal_campaign_id_public_id");

                    b.HasIndex("WorkItemId", "PublicId")
                        .HasDatabaseName("ix_journal_work_item_id_public_id");

                    b.ToTable("journal", null, t =>
                        {
                            t.HasCheckConstraint("ck_journal_new_json", "new_json IS NULL OR json_valid(new_json)");

                            t.HasCheckConstraint("ck_journal_old_json", "old_json IS NULL OR json_valid(old_json)");
                        });
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Account")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("account");

                    b.Property<string>("Assertion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("assertion_json");

                    b.Property<string>("AssertionHash")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("assertion_hash");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("campaign_id");

                    b.Property<int?>("ContactId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("contact_id");

                    b.Property<bool?>("ContactInCampaign")
                        .HasColumnType("INTEGER")
                        .HasColumnName("contact_in_campaign");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("effect");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTime?>("ObservedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("observed_at");

                    b.Property<DateTime?>("OccurredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Operation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("operation");

                    b.Property<bool>("OperationKnown")
                        .HasColumnType("INTEGER")
                        .HasColumnName("operation_known");

                    b.Property<string>("Provider")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("received_at");

                    b.Property<string>("ReporterId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("reporter_id");

                    b.Property<string>("ReporterType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("reporter_type");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("tool");

                    b.Property<int?>("WorkItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_reports_campaign_id");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_reports_contact_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_reports_public_id");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_reports_received_at");

                    b.HasIndex("WorkItemId")
                        .HasDatabaseName("ix_reports_work_item_id");

                    b.HasIndex("ReporterType", "ReporterId", "AssertionHash")
                        .IsUnique()
                        .HasDatabaseName("ix_reports_one_per_reporter_content")
                        .HasFilter("idempotency_key IS NULL");

                    b.HasIndex("ReporterType", "ReporterId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_reports_one_per_reporter_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.ToTable("reports", t =>
                        {
                            t.HasCheckConstraint("ck_reports_assertion_json", "json_valid(assertion_json)");
                        });
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Builtin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("builtin");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("EntryCommand")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_command_json")
                        .HasDefaultValueSql("'[]'");

                    b.Property<string>("ExecutionProfile")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_profile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ProfileDefaults")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("profile_defaults_json")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_public_id");

                    b.ToTable("roles", t =>
                        {
                            t.HasCheckConstraint("ck_roles_entry_command_json", "json_valid(entry_command_json)");

                            t.HasCheckConstraint("ck_roles_profile_defaults_json", "json_valid(profile_defaults_json)");
                        });
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.RoleNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("note_json")
                        .HasDefaultValueSql("'{}'");

                    b.Property<long>("NoteBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("note_bytes");

                    b.Property<string>("NoteHash")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("note_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_id");

                    b.Property<string>("UpdatedByType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by_type");

                    b.HasKey("Id")
                        .HasName("pk_role_notes");

                    b.HasIndex("CampaignId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ix_role_notes_one_per_campaign_role");

                    b.ToTable("role_notes", t =>
                        {
                            t.HasCheckConstraint("ck_role_notes_note_json", "json_valid(note_json)");
                        });
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.Suppression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_suppressions");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_suppressions_public_id");

                    b.HasIndex("Channel", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_suppressions_channel_value");

                    b.ToTable("suppressions");
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_count");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("campaign_id");

                    b.Property<int?>("ContactId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("contact_id");

                    b.Property<string>("Context")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("context_json")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CreatedByType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_type");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_at");

                    b.Property<string>("ExecutionProfile")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_profile");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<int?>("HeartbeatSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("heartbeat_seconds");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error_json");

                    b.Property<string>("LineageFromAttemptId")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("lineage_from_attempt_id");

                    b.Property<string>("LineageProfileName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("lineage_profile_name");

                    b.Property<int?>("LineageProfileRevision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lineage_profile_revision");

                    b.Property<string>("LineageState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("lineage_state");

                    b.Property<int?>("MaxAttempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_attempts");

                    b.Property<DateTime?>("NotBefore")
                        .HasColumnType("TEXT")
                        .HasColumnName("not_before");

                    b.Property<string>("Operation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("operation");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_json");

                    b.Property<string>("ResultFormat")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_format_json");

                    b.Property<DateTime?>("RetryAfter")
                        .HasColumnType("TEXT")
                        .HasColumnName("retry_after");

                    b.Property<string>("Role")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_work_items");

                    b.HasIndex("CampaignId")
                        .IsUnique()
                        .HasDatabaseName("ix_work_items_one_open_check_in_per_campaign")
                        .HasFilter("role = 'manager' AND created_by_type = 'system' AND status IN ('created','scheduled','processing','awaiting_approval')");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("ix_work_items_contact_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_work_items_public_id");

                    b.HasIndex("CampaignId", "Status")
                        .HasDatabaseName("ix_work_items_campaign_id_status");

                    b.HasIndex("Status", "DueAt")
                        .HasDatabaseName("ix_work_items_status_due_at");

                    b.HasIndex("Status", "NotBefore")
                        .HasDatabaseName("ix_work_items_status_not_before");

                    b.ToTable("work_items", t =>
                        {
                            t.HasCheckConstraint("ck_work_items_context_json", "json_valid(context_json)");

                            t.HasCheckConstraint("ck_work_items_last_error_json", "last_error_json IS NULL OR json_valid(last_error_json)");

                            t.HasCheckConstraint("ck_work_items_result_format_json", "result_format_json IS NULL OR json_valid(result_format_json)");

                            t.HasCheckConstraint("ck_work_items_result_json", "result_json IS NULL OR json_valid(result_json)");
                        });
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.Approval", b =>
                {
                    b.HasOne("Jason.Runtime.Persistence.WorkItem", "WorkItem")
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_approvals_work_items_work_item_id");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.Attempt", b =>
                {
                    b.HasOne("Jason.Runtime.Persistence.WorkItem", "WorkItem")
                        .WithMany("Attempts")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attempts_work_items_work_item_id");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.CampaignContact", b =>
                {
                    b.HasOne("Jason.Runtime.Persistence.Campaign", "Campaign")
                        .WithMany("Members")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_contacts_campaigns_campaign_id");

                    b.HasOne("Jason.Runtime.Persistence.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_contacts_contacts_contact_id");

                    b.Navigation("Campaign");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.CampaignRoute", b =>
                {
                    b.HasOne("Jason.Runtime.Persistence.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_routes_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.ContactChannel", b =>
                {
                    b.HasOne("Jason.Runtime.Persistence.Contact", "Contact")
                        .WithMany("Channels")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_channels_contacts_contact_id");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.Decision", b =>
                {
                    b.HasOne("Jason.Runtime.Persistence.Attempt", "Attempt")
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_decisions_attempts_attempt_id");

                    b.HasOne("Jason.Runtime.Persistence.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_decisions_campaigns_campaign_id");

                    b.HasOne("Jason.Runtime.Persistence.WorkItem", "WorkItem")
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_decisions_work_items_work_item_id");

                    b.Navigation("Attempt");

                    b.Navigation("Campaign");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.ExecutionProfileRevision", b =>
                {
                    b.HasOne("Jason.Runtime.Persistence.ExecutionProfile", "Profile")
                        .WithMany("Revisions")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_execution_profile_revisions_execution_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.ExternalId", b =>
                {
                    b.HasOne("Jason.Runtime.Persistence.Campaign", "Campaign")
                        .WithMany("ExternalIds")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_external_ids_campaigns_campaign_id");

                    b.HasOne("Jason.Runtime.Persistence.Contact", "Contact")
                        .WithMany("ExternalIds")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_external_ids_contacts_contact_id");

                    b.Navigation("Campaign");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.JournalEntry", b =>
                {
                    b.HasOne("Jason.Runtime.Persistence.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_journal_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.Report", b =>
                {
                    b.HasOne("Jason.Runtime.Persistence.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reports_campaigns_campaign_id");

                    b.HasOne("Jason.Runtime.Persistence.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reports_contacts_contact_id");

                    b.HasOne("Jason.Runtime.Persistence.WorkItem", "WorkItem")
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reports_work_items_work_item_id");

                    b.Navigation("Campaign");

                    b.Navigation("Contact");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.RoleNote", b =>
                {
                    b.HasOne("Jason.Runtime.Persistence.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_notes_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.WorkItem", b =>
                {
                    b.HasOne("Jason.Runtime.Persistence.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_items_campaigns_campaign_id");

                    b.HasOne("Jason.Runtime.Persistence.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_work_items_contacts_contact_id");

                    b.Navigation("Campaign");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.Campaign", b =>
                {
                    b.Navigation("ExternalIds");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.Contact", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("ExternalIds");
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.ExecutionProfile", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Jason.Runtime.Persistence.WorkItem", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
